### ISSUE TITLE
themes - plural

### ISSUE THREAD

**Issue by xixianykus** [J-Siu/hugo-theme-sk1#1]
In the readme file to clone or submodule the link says theme:

git clone https://github.com/J-Siu/hugo-theme-sk1 theme/sk1
git submodule add https://github.com/J-Siu/hugo-theme-sk1 theme/sk1

It should say _themes_ to refer to the folder where the themes are stored. In the config file though it's still _theme="sk1"_ as you can only use one theme at a time.

**Comment by J-Siu** [comment]
Thank you! Fixing now.
